name: Deploy Dockerized Node.js app to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: monregistryxyz.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t monregistryxyz.azurecr.io/visit-counter-app:latest .
          docker push monregistryxyz.azurecr.io/visit-counter-app:latest