name: Deploy Dockerized Node.js app to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: azudocker-eaewuebpdshxdzfb.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}  # ⚠️ doit exister dans GitHub Secrets
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}  # ⚠️ doit exister dans GitHub Secrets

      - name: Build and push Docker image
        run: |
          docker build -t azudocker-eaewuebpdshxdzfb.azurecr.io/azuredocker:latest .
          docker push azudocker-eaewuebpdshxdzfb.azurecr.io/azuredocker:latest
